Q1. Import numpy as np and print the version number

In [52]:
import numpy as np
print(np.__version__)

1.18.1


Q2. Create a 1D array of numbers from 0 to 9

In [28]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 Q3. Create a 3×3 numpy array of all True’s

In [22]:
np.full((3,3),True,dtype=bool)
# Alternate method is
#np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

 Q4. Extract all odd numbers from arr

In [23]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

 Q5. Replace all odd numbers in arr with -1

In [25]:
arr[arr % 2 != 0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

 Q6. Replace all odd numbers in arr with -1 without changing arr

In [29]:
print(arr)
out = np.where(arr % 2 != 0,-1,arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

 Q7. Convert a 1D array to a 2D array with 2 rows

In [31]:
arr.reshape((2,5))
#arr.reshape(2, -1)  
# Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

 Q8. Stack arrays a and b vertically

In [36]:
a=np.arange(10).reshape((2,-1))
b=np.repeat(1,10).reshape((2,-1))
np.concatenate((a,b),axis=0)
#np.vstack([a,b])
#np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

 Q9. Stack the arrays a and b horizontally.

In [37]:
np.concatenate((a,b),axis=1)
#Alternatives
#np.hstack([a,b])
#np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# Q10. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
Input: a=np.array([1,2,3])

Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [48]:
a=np.array([1,2,3])
np.hstack([np.repeat(a,3),np.tile(a,3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

 Q11. Get the common items between a and b

In [50]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# Get common values from above two arrays
np.intersect1d(a,b)

array([2, 4])

 Q12.From array a remove all items present in array b

In [54]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

Q13. Get the positions where elements of a and b match

In [57]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

Q14. Get all items between 5 and 10 from a

In [67]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5) & (a<=10)]
# index=np.where(np.logical_and(a>=5, a<=10))
#a[index]
#or
# index=np.where((a>=5)&(a<=10)
#a[index]

array([ 6,  9, 10])

Q15. How to make a python function that handles scalars to work on numpy arrays?

In [69]:
def maxx(x,y):
    """Get the maximum of two"""
    if x >= y:
        return x
    else:
        return y
pair_max=np.vectorize(maxx, otypes=[float])
a=np.array([5,7,9,8,6,4,5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

Q16. Swap columns 1 and 2 in the array arr

In [72]:
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Q17. Swap rows 1 and 2 in the array arr:

In [74]:
arr= np.arange(9).reshape(3,3)
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

Q18. Reverse the rows of a 2D array arr.

In [102]:
arr= np.arange(9).reshape((3,3))
#arr[[2,1,0],:]
# or
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

Q19. Reverse the columns of a 2D array arr.

In [103]:
arr = np.arange(9).reshape((3,3))
arr[:,[2,1,0]]
#or
#arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

Q20. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [107]:
arr= np.random.uniform(5,10,size=(5,3))
arr

array([[7.790982  , 7.98200319, 6.7624285 ],
       [8.21686147, 5.79935102, 7.85121651],
       [7.21629771, 9.72077569, 7.31949743],
       [6.86693762, 8.96319152, 6.35475411],
       [5.67839305, 9.10032484, 9.96546057]])

Q21.Print or show only 3 decimal places of the numpy array rand_arr.

In [110]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr[:]

array([[0.219, 0.128, 0.086],
       [0.031, 0.646, 0.314],
       [0.15 , 0.16 , 0.888],
       [0.787, 0.231, 0.587],
       [0.026, 0.258, 0.067]])

Q22. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [120]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

Q23. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [148]:
np.set_printoptions(threshold=6)
a= np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

Q24. Print the full numpy array a without truncating.

In [152]:
a=np.arange(15)
np.set_printoptions(threshold=np.inf)
# inf stands for infinity
print(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Q25. Import the iris dataset keeping the text intact

In [156]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:10]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa']], dtype=object)

Q26. Use linespace function of numpy

In [168]:
from numpy import pi
x=np.linspace(0,2*pi,100).reshape(20,5)
f=np.sin(x)
print(f)

[[ 0.        0.063424  0.126592  0.189251  0.251148]
 [ 0.312033  0.371662  0.429795  0.486197  0.540641]
 [ 0.592908  0.642788  0.690079  0.734592  0.776146]
 [ 0.814576  0.849725  0.881453  0.909632  0.934148]
 [ 0.954902  0.971812  0.984808  0.993838  0.998867]
 [ 0.999874  0.996855  0.989821  0.978802  0.963842]
 [ 0.945001  0.922354  0.895994  0.866025  0.83257 ]
 [ 0.795762  0.75575   0.712694  0.666769  0.618159]
 [ 0.56706   0.513677  0.458227  0.400931  0.34202 ]
 [ 0.281733  0.220311  0.158001  0.095056  0.031728]
 [-0.031728 -0.095056 -0.158001 -0.220311 -0.281733]
 [-0.34202  -0.400931 -0.458227 -0.513677 -0.56706 ]
 [-0.618159 -0.666769 -0.712694 -0.75575  -0.795762]
 [-0.83257  -0.866025 -0.895994 -0.922354 -0.945001]
 [-0.963842 -0.978802 -0.989821 -0.996855 -0.999874]
 [-0.998867 -0.993838 -0.984808 -0.971812 -0.954902]
 [-0.934148 -0.909632 -0.881453 -0.849725 -0.814576]
 [-0.776146 -0.734592 -0.690079 -0.642788 -0.592908]
 [-0.540641 -0.486197 -0.429795 -0.371662 -0.3

# Basic operations

In [162]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )

Element Wise Product

In [163]:
A*B

array([[2, 0],
       [0, 4]])

Matrix Product

In [165]:
A@B

array([[5, 4],
       [3, 4]])

Another Matrix multiplication using dot() method of numpy

In [166]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [170]:
a=np.random.random((2,3))
a

array([[0.575093, 0.891322, 0.209202],
       [0.185328, 0.108377, 0.219697]])

Sum of array

In [171]:
a.sum()

2.1890200084960263

Minimum value from array

In [172]:
a.min()

0.10837689046425514

Maximum value from array

In [173]:
a.max()

0.891321954312264

# Operations in ndArray

In [175]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Sum of Each Column

In [179]:
b.sum(axis=0)

array([12, 15, 18, 21])

Minimum of each Row

In [183]:
b.min(axis=1)

array([0, 4, 8])

Cummulative sum along each row

In [184]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

# Universal Function

In [186]:
B= np.arange(5)
B

array([0, 1, 2, 3, 4])

Find Square root of each value in Array

In [189]:
np.set_printoptions(precision=3)
np.sqrt(B)

array([0.   , 1.   , 1.414, 1.732, 2.   ])

Find mean of array

In [191]:
np.mean(B)

2.0

Find the Median of array

In [202]:

np.median(B)

2.0

Find the variance 

In [206]:
a=np.random.randint(1,100,15).reshape(3,5)
np.var(a)

1115.3155555555556

Find the Standard deviation

In [211]:
np.std(a)

33.39634045154582

Find The Tranpose of Two Dimensional array

In [212]:
np.transpose(a)

array([[90, 87, 21],
       [46, 83, 11],
       [36, 68,  9],
       [17, 93, 90],
       [13, 96, 73]])

# Indexing And Slicing 

In [215]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
                [[100,101,102],
                 [110,112,113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

Find the shape of matrices

In [217]:
c.shape

(2, 2, 3)

In [221]:
c[1,...] # same as c[ :, : ,1] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [243]:
c[ :, :, 2] # same as c[:,:,2] select 2nd coumn if eacj vector

array([[  2,  13],
       [102, 113]])

# Shape Manipulation

In [246]:
a = np.floor(10*np.random.random((3,4)))
a

array([[4., 6., 5., 7.],
       [5., 0., 3., 4.],
       [4., 3., 5., 4.]])

Return the faltten array

In [250]:
np.ravel(a)

array([4., 6., 5., 7., 5., 0., 3., 4., 4., 3., 5., 4.])

Reshape the Above array a

In [251]:
a.reshape(6,2)

array([[4., 6.],
       [5., 7.],
       [5., 0.],
       [3., 4.],
       [4., 3.],
       [5., 4.]])

# Staking Together Different  arrays

In [253]:
from numpy import random as rg
a = np.floor(10*rg.random((2,2)))
b = np.floor(10*rg.random((2,2)))

In [256]:
print(a,"\n\n",b)

[[9. 9.]
 [1. 6.]] 

 [[5. 1.]
 [9. 2.]]


In [263]:
np.vstack((a,b)) # Equavalent to np.concatenate((a,b),axis=0)

array([[9., 9.],
       [1., 6.],
       [5., 1.],
       [9., 2.]])

In [264]:
np.hstack((a,b)) #Equavalent to np.concatenate((a,b),axis=1)

array([[9., 9., 5., 1.],
       [1., 6., 9., 2.]])

In [265]:
np.column_stack is np.hstack

False

In [266]:
np.row_stack is np.vstack

True

# The End